/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SignInImport } from './routes/sign-in'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as AuthedImport } from './routes/_authed'
import { Route as VideoIdImport } from './routes/$videoId'
import { Route as IndexImport } from './routes/index'
import { Route as AuthCallbackImport } from './routes/auth/callback'
import { Route as AuthedSettingsImport } from './routes/_authed.settings'
import { Route as AuthedProfileImport } from './routes/_authed.profile'
import { Route as AuthedDashboardImport } from './routes/_authed.dashboard'
import { Route as AuthedJobsJobIdImport } from './routes/_authed.jobs.$jobId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const VideoIdRoute = VideoIdImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthedSettingsRoute = AuthedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedProfileRoute = AuthedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedJobsJobIdRoute = AuthedJobsJobIdImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$videoId': {
      id: '/$videoId'
      path: '/$videoId'
      fullPath: '/$videoId'
      preLoaderRoute: typeof VideoIdImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsImport
      parentRoute: typeof AuthedImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authed/jobs/$jobId': {
      id: '/_authed/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthedJobsJobIdImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedJobsJobIdRoute: typeof AuthedJobsJobIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedJobsJobIdRoute: AuthedJobsJobIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$videoId': typeof VideoIdRoute
  '': typeof PathlessLayoutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$videoId': typeof VideoIdRoute
  '': typeof PathlessLayoutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$videoId': typeof VideoIdRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/jobs/$jobId': typeof AuthedJobsJobIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$videoId'
    | ''
    | '/login'
    | '/logout'
    | '/sign-in'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$videoId'
    | ''
    | '/login'
    | '/logout'
    | '/sign-in'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/$videoId'
    | '/_authed'
    | '/_pathlessLayout'
    | '/login'
    | '/logout'
    | '/sign-in'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/settings'
    | '/auth/callback'
    | '/_authed/jobs/$jobId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoIdRoute: typeof VideoIdRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignInRoute: typeof SignInRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoIdRoute: VideoIdRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignInRoute: SignInRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$videoId",
        "/_authed",
        "/_pathlessLayout",
        "/login",
        "/logout",
        "/sign-in",
        "/signup",
        "/auth/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$videoId": {
      "filePath": "$videoId.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard",
        "/_authed/profile",
        "/_authed/settings",
        "/_authed/jobs/$jobId"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed.dashboard.tsx",
      "parent": "/_authed"
    },
    "/_authed/profile": {
      "filePath": "_authed.profile.tsx",
      "parent": "/_authed"
    },
    "/_authed/settings": {
      "filePath": "_authed.settings.tsx",
      "parent": "/_authed"
    },
    "/auth/callback": {
      "filePath": "auth/callback.tsx"
    },
    "/_authed/jobs/$jobId": {
      "filePath": "_authed.jobs.$jobId.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
