/**
 * Database types - single source of truth from Supabase schema.
 *
 * These types are automatically synced from packages/supabase/types/database.ts
 * which is generated by the Supabase CLI from the live database schema.
 */

// Import the types we need from the Supabase package
import type { Database } from '../../supabase/types/database';

// Re-export the main types
export type { Database, Enums } from '../../supabase/types/database';

// Helper types for better DX
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// The actual types you'll use - these come directly from the database
export type Video = Tables<'videos'>
export type VideoJob = Tables<'video_jobs'>
export type VideoMetadata = Tables<'video_metadata'>

export type VideoInsert = TablesInsert<'videos'>
export type VideoJobInsert = TablesInsert<'video_jobs'>
export type VideoMetadataInsert = TablesInsert<'video_metadata'>

export type VideoUpdate = TablesUpdate<'videos'>
export type VideoJobUpdate = TablesUpdate<'video_jobs'>
export type VideoMetadataUpdate = TablesUpdate<'video_metadata'>
