/**
 * Auto-generated TypeScript types from Pydantic API schemas.
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * 
 * This file is generated by apps/core/bin/generate_api_types.py
 * Run `pnpm codegen:api-types` to regenerate.
 */


export enum ProcessingStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export interface VideoResponse {
  id: number;
  uploader_user_id: string;
  original_filename: string;
  storage_path: string;
  content_type: string;
  size_bytes: number;
  created_at: string;
  updated_at: string;
}

export interface VideoJobResponse {
  id: number;
  video_id: number;
  status: ProcessingStatus;
  processing_stages?: Record<string, any> | null;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
}

export interface VideoMetadataResponse {
  id: number;
  job_id: number;
  title?: string | null;
  description?: string | null;
  tags?: string[] | null;
  transcript_text?: string | null;
  transcript_file_url?: string | null;
  subtitle_files_urls?: Record<string, string> | null;
  thumbnail_file_url?: string | null;
  extracted_video_duration_seconds?: number | null;
  extracted_video_resolution?: string | null;
  extracted_video_format?: string | null;
  show_notes_text?: string | null;
  created_at: string;
  updated_at: string;
}

export interface VideoSummary {
  id: number;
  original_filename: string;
  title?: string | null;
  thumbnail_file_url?: string | null;
  created_at: string;
  status?: ProcessingStatus | null;
}

export interface VideoUploadResponse {
  video_id: number;
  job_id: number;
  status: ProcessingStatus;
}

export interface VideoWithJobsResponse {
  id: number;
  uploader_user_id: string;
  original_filename: string;
  storage_path: string;
  content_type: string;
  size_bytes: number;
  created_at: string;
  updated_at: string;
  jobs?: VideoJobResponseSchema[];
}

export interface VideoJobWithDetailsResponse {
  id: number;
  video_id: number;
  status: ProcessingStatus;
  processing_stages?: Record<string, any> | null;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
  video: VideoResponseSchema;
  video_metadata?: VideoMetadataResponseSchema | null;
}

export interface VideoMetadataUpdateRequest {
  title?: string | null;
  description?: string | null;
  tags?: string[] | null;
}

export interface SignedUploadUrlResponse {
  upload_url: string;
  video_id: string;
}

export interface VideoSummaryLegacy {
  id: number;
  original_filename: string;
  title?: string | null;
  created_at?: string | null;
  status?: ProcessingStatus | null;
  thumbnail_file_url?: string | null;
}

export interface Video {
  id: number;
  uploader_user_id: string;
  original_filename: string;
  storage_path: string;
  content_type: string;
  size_bytes: number;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface VideoMetadata {
  id?: number | null;
  job_id?: number | null;
  title?: string | null;
  description?: string | null;
  tags?: string[] | null;
  transcript_text?: string | null;
  transcript_file_url?: string | null;
  subtitle_files_urls?: Record<string, any> | null;
  thumbnail_file_url?: string | null;
  extracted_video_duration_seconds?: number | null;
  extracted_video_resolution?: string | null;
  extracted_video_format?: string | null;
  show_notes_text?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface VideoJob {
  id: number;
  video_id: number;
  status: ProcessingStatus;
  processing_stages?: string[] | Record<string, any> | null;
  error_message?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  video?: VideoSchema | null;
  metadata?: VideoMetadataSchema | null;
}

export interface VideoDetailsResponse {
  id: number;
  video_id: number;
  uploader_user_id?: string | null;
  original_filename?: string | null;
  status: ProcessingStatus;
  processing_stages?: string[] | Record<string, any> | null;
  error_message?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  video?: VideoSchema | null;
  metadata?: VideoMetadataSchema | null;
}
